name: baseshift
summary: BaseShift
description: |
  A CLI application converting numbers Systems. This will support
  binary, decimal, octal, and hexadecimal systems.
version: "1.2"
grade: stable
base: core20
confinement: strict
apps:
  baseshift:
    command: bin/baseshift
parts:
  baseshift:
    plugin: go
    source-type: git
    source: https://github.com/kentlouisetonino/baseshift.git
